CREATE DATABASE BDMIGRANA;

USE BDMIGRANA;

CREATE TABLE USUARIOS(
    ID INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE GRAFICAS(
    ID INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    TIPO_ID INTEGER(11),
    SUPER_DESCRIPCION TEXT NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    DATASET_ID INTEGER(11)

);


CREATE TABLE TIPO_GRAFICAS(
    ID INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    IMAGEN BLOB,
    DESCRIPCION TEXT NOT NULL
);


CREATE TABLE DATASETS(
    ID INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);


CREATE TABLE COMENTARIOS(
   ID INTEGER(11) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
    USER_ID INTEGER(11),
    GRAFICA_ID INTEGER(11),
    COMENTARIO TEXT NOT NULL,
    FECHA TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE GRAFICAS ADD CONSTRAINT FK_GRAFICA_TIPO_GRAFICA
FOREIGN KEY (TIPO_ID) REFERENCES TIPO_GRAFICAS(ID);

ALTER TABLE GRAFICAS ADD CONSTRAINT FK_GRAFICA_DATASET
FOREIGN KEY (DATASET_ID) REFERENCES DATASETS(ID);




ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIO_USUARIO
FOREIGN KEY (USER_ID) REFERENCES USUARIOS(ID);

ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIO_GRAFICA
FOREIGN KEY (GRAFICA_ID) REFERENCES GRAFICAS(ID);



CREATE TABLE users(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(60) NOT NULL,
    name VARCHAR(100) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL
);

CREATE TABLE links (
    id INT(11) NOT NULL,
    title VARCHAR(150) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT,
    user_id INT(11),
    created_at timestamp NOT NULL DEFAULT current_timestamp,
    
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE links
    ADD PRIMARY KEY (id);

ALTER TABLE links
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT;


